// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Snakes.proto

package Snakes;

public interface GamePlayersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:snakes.GamePlayers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  java.util.List<Snakes.GamePlayer> 
      getPlayersList();
  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  Snakes.GamePlayer getPlayers(int index);
  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  int getPlayersCount();
  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  java.util.List<? extends Snakes.GamePlayerOrBuilder> 
      getPlayersOrBuilderList();
  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  Snakes.GamePlayerOrBuilder getPlayersOrBuilder(
      int index);
}
