// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Snakes.proto

package Snakes;

public interface GameStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:snakes.GameState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Порядковый номер состояния, уникален в пределах игры, монотонно возрастает
   * </pre>
   *
   * <code>required int32 state_order = 1;</code>
   * @return Whether the stateOrder field is set.
   */
  boolean hasStateOrder();
  /**
   * <pre>
   * Порядковый номер состояния, уникален в пределах игры, монотонно возрастает
   * </pre>
   *
   * <code>required int32 state_order = 1;</code>
   * @return The stateOrder.
   */
  int getStateOrder();

  /**
   * <pre>
   * Список змей
   * </pre>
   *
   * <code>repeated .snakes.GameState.Snake snakes = 2;</code>
   */
  java.util.List<Snakes.GameState.Snake> 
      getSnakesList();
  /**
   * <pre>
   * Список змей
   * </pre>
   *
   * <code>repeated .snakes.GameState.Snake snakes = 2;</code>
   */
  Snakes.GameState.Snake getSnakes(int index);
  /**
   * <pre>
   * Список змей
   * </pre>
   *
   * <code>repeated .snakes.GameState.Snake snakes = 2;</code>
   */
  int getSnakesCount();
  /**
   * <pre>
   * Список змей
   * </pre>
   *
   * <code>repeated .snakes.GameState.Snake snakes = 2;</code>
   */
  java.util.List<? extends Snakes.GameState.SnakeOrBuilder> 
      getSnakesOrBuilderList();
  /**
   * <pre>
   * Список змей
   * </pre>
   *
   * <code>repeated .snakes.GameState.Snake snakes = 2;</code>
   */
  Snakes.GameState.SnakeOrBuilder getSnakesOrBuilder(
      int index);

  /**
   * <pre>
   * Список клеток с едой
   * </pre>
   *
   * <code>repeated .snakes.GameState.Coord foods = 3;</code>
   */
  java.util.List<Snakes.GameState.Coord> 
      getFoodsList();
  /**
   * <pre>
   * Список клеток с едой
   * </pre>
   *
   * <code>repeated .snakes.GameState.Coord foods = 3;</code>
   */
  Snakes.GameState.Coord getFoods(int index);
  /**
   * <pre>
   * Список клеток с едой
   * </pre>
   *
   * <code>repeated .snakes.GameState.Coord foods = 3;</code>
   */
  int getFoodsCount();
  /**
   * <pre>
   * Список клеток с едой
   * </pre>
   *
   * <code>repeated .snakes.GameState.Coord foods = 3;</code>
   */
  java.util.List<? extends Snakes.GameState.CoordOrBuilder> 
      getFoodsOrBuilderList();
  /**
   * <pre>
   * Список клеток с едой
   * </pre>
   *
   * <code>repeated .snakes.GameState.Coord foods = 3;</code>
   */
  Snakes.GameState.CoordOrBuilder getFoodsOrBuilder(
      int index);

  /**
   * <pre>
   * Актуальнейший список игроков
   * </pre>
   *
   * <code>required .snakes.GamePlayers players = 4;</code>
   * @return Whether the players field is set.
   */
  boolean hasPlayers();
  /**
   * <pre>
   * Актуальнейший список игроков
   * </pre>
   *
   * <code>required .snakes.GamePlayers players = 4;</code>
   * @return The players.
   */
  Snakes.GamePlayers getPlayers();
  /**
   * <pre>
   * Актуальнейший список игроков
   * </pre>
   *
   * <code>required .snakes.GamePlayers players = 4;</code>
   */
  Snakes.GamePlayersOrBuilder getPlayersOrBuilder();

  /**
   * <pre>
   * Параметры игры
   * </pre>
   *
   * <code>required .snakes.GameConfig config = 5;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <pre>
   * Параметры игры
   * </pre>
   *
   * <code>required .snakes.GameConfig config = 5;</code>
   * @return The config.
   */
  Snakes.GameConfig getConfig();
  /**
   * <pre>
   * Параметры игры
   * </pre>
   *
   * <code>required .snakes.GameConfig config = 5;</code>
   */
  Snakes.GameConfigOrBuilder getConfigOrBuilder();
}
