// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Snakes.proto

package Snakes;

/**
 * <pre>
 * Параметры идущей игры (не должны меняться в процессе игры) 
 * </pre>
 *
 * Protobuf type {@code snakes.GameConfig}
 */
public final class GameConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:snakes.GameConfig)
    GameConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GameConfig.newBuilder() to construct.
  private GameConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GameConfig() {
    width_ = 40;
    height_ = 30;
    foodStatic_ = 1;
    foodPerPlayer_ = 1F;
    stateDelayMs_ = 1000;
    deadFoodProb_ = 0.1F;
    pingDelayMs_ = 100;
    nodeTimeoutMs_ = 800;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GameConfig();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GameConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            width_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            height_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            foodStatic_ = input.readInt32();
            break;
          }
          case 37: {
            bitField0_ |= 0x00000008;
            foodPerPlayer_ = input.readFloat();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            stateDelayMs_ = input.readInt32();
            break;
          }
          case 53: {
            bitField0_ |= 0x00000020;
            deadFoodProb_ = input.readFloat();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            pingDelayMs_ = input.readInt32();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000080;
            nodeTimeoutMs_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Snakes.SnakesProto.internal_static_snakes_GameConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Snakes.SnakesProto.internal_static_snakes_GameConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Snakes.GameConfig.class, Snakes.GameConfig.Builder.class);
  }

  private int bitField0_;
  public static final int WIDTH_FIELD_NUMBER = 1;
  private int width_;
  /**
   * <pre>
   * Ширина поля в клетках (от 10 до 100)
   * </pre>
   *
   * <code>optional int32 width = 1 [default = 40];</code>
   * @return Whether the width field is set.
   */
  @java.lang.Override
  public boolean hasWidth() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Ширина поля в клетках (от 10 до 100)
   * </pre>
   *
   * <code>optional int32 width = 1 [default = 40];</code>
   * @return The width.
   */
  @java.lang.Override
  public int getWidth() {
    return width_;
  }

  public static final int HEIGHT_FIELD_NUMBER = 2;
  private int height_;
  /**
   * <pre>
   * Высота поля в клетках (от 10 до 100)
   * </pre>
   *
   * <code>optional int32 height = 2 [default = 30];</code>
   * @return Whether the height field is set.
   */
  @java.lang.Override
  public boolean hasHeight() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Высота поля в клетках (от 10 до 100)
   * </pre>
   *
   * <code>optional int32 height = 2 [default = 30];</code>
   * @return The height.
   */
  @java.lang.Override
  public int getHeight() {
    return height_;
  }

  public static final int FOOD_STATIC_FIELD_NUMBER = 3;
  private int foodStatic_;
  /**
   * <pre>
   * Количество клеток с едой, независимо от числа игроков (от 0 до 100)
   * </pre>
   *
   * <code>optional int32 food_static = 3 [default = 1];</code>
   * @return Whether the foodStatic field is set.
   */
  @java.lang.Override
  public boolean hasFoodStatic() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Количество клеток с едой, независимо от числа игроков (от 0 до 100)
   * </pre>
   *
   * <code>optional int32 food_static = 3 [default = 1];</code>
   * @return The foodStatic.
   */
  @java.lang.Override
  public int getFoodStatic() {
    return foodStatic_;
  }

  public static final int FOOD_PER_PLAYER_FIELD_NUMBER = 4;
  private float foodPerPlayer_;
  /**
   * <pre>
   * Количество клеток с едой, на каждого игрока (вещественный коэффициент от 0 до 100)
   * </pre>
   *
   * <code>optional float food_per_player = 4 [default = 1];</code>
   * @return Whether the foodPerPlayer field is set.
   */
  @java.lang.Override
  public boolean hasFoodPerPlayer() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Количество клеток с едой, на каждого игрока (вещественный коэффициент от 0 до 100)
   * </pre>
   *
   * <code>optional float food_per_player = 4 [default = 1];</code>
   * @return The foodPerPlayer.
   */
  @java.lang.Override
  public float getFoodPerPlayer() {
    return foodPerPlayer_;
  }

  public static final int STATE_DELAY_MS_FIELD_NUMBER = 5;
  private int stateDelayMs_;
  /**
   * <pre>
   * Задержка между ходами (сменой состояний) в игре, в миллисекундах (от 1 до 10000)
   * </pre>
   *
   * <code>optional int32 state_delay_ms = 5 [default = 1000];</code>
   * @return Whether the stateDelayMs field is set.
   */
  @java.lang.Override
  public boolean hasStateDelayMs() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * Задержка между ходами (сменой состояний) в игре, в миллисекундах (от 1 до 10000)
   * </pre>
   *
   * <code>optional int32 state_delay_ms = 5 [default = 1000];</code>
   * @return The stateDelayMs.
   */
  @java.lang.Override
  public int getStateDelayMs() {
    return stateDelayMs_;
  }

  public static final int DEAD_FOOD_PROB_FIELD_NUMBER = 6;
  private float deadFoodProb_;
  /**
   * <pre>
   * Вероятность превращения мёртвой клетки в еду (от 0 до 1).
   * </pre>
   *
   * <code>optional float dead_food_prob = 6 [default = 0.1];</code>
   * @return Whether the deadFoodProb field is set.
   */
  @java.lang.Override
  public boolean hasDeadFoodProb() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * Вероятность превращения мёртвой клетки в еду (от 0 до 1).
   * </pre>
   *
   * <code>optional float dead_food_prob = 6 [default = 0.1];</code>
   * @return The deadFoodProb.
   */
  @java.lang.Override
  public float getDeadFoodProb() {
    return deadFoodProb_;
  }

  public static final int PING_DELAY_MS_FIELD_NUMBER = 7;
  private int pingDelayMs_;
  /**
   * <pre>
   * Задержка между отправкой ping-сообщений, в миллисекундах (от 1 до 10000)
   * </pre>
   *
   * <code>optional int32 ping_delay_ms = 7 [default = 100];</code>
   * @return Whether the pingDelayMs field is set.
   */
  @java.lang.Override
  public boolean hasPingDelayMs() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   * Задержка между отправкой ping-сообщений, в миллисекундах (от 1 до 10000)
   * </pre>
   *
   * <code>optional int32 ping_delay_ms = 7 [default = 100];</code>
   * @return The pingDelayMs.
   */
  @java.lang.Override
  public int getPingDelayMs() {
    return pingDelayMs_;
  }

  public static final int NODE_TIMEOUT_MS_FIELD_NUMBER = 8;
  private int nodeTimeoutMs_;
  /**
   * <pre>
   * Таймаут, после которого считаем что узел-сосед отпал, в миллисекундах (от 1 до 10000)
   * </pre>
   *
   * <code>optional int32 node_timeout_ms = 8 [default = 800];</code>
   * @return Whether the nodeTimeoutMs field is set.
   */
  @java.lang.Override
  public boolean hasNodeTimeoutMs() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <pre>
   * Таймаут, после которого считаем что узел-сосед отпал, в миллисекундах (от 1 до 10000)
   * </pre>
   *
   * <code>optional int32 node_timeout_ms = 8 [default = 800];</code>
   * @return The nodeTimeoutMs.
   */
  @java.lang.Override
  public int getNodeTimeoutMs() {
    return nodeTimeoutMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, width_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, height_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, foodStatic_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeFloat(4, foodPerPlayer_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, stateDelayMs_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeFloat(6, deadFoodProb_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeInt32(7, pingDelayMs_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeInt32(8, nodeTimeoutMs_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, width_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, height_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, foodStatic_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, foodPerPlayer_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, stateDelayMs_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, deadFoodProb_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, pingDelayMs_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, nodeTimeoutMs_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Snakes.GameConfig)) {
      return super.equals(obj);
    }
    Snakes.GameConfig other = (Snakes.GameConfig) obj;

    if (hasWidth() != other.hasWidth()) return false;
    if (hasWidth()) {
      if (getWidth()
          != other.getWidth()) return false;
    }
    if (hasHeight() != other.hasHeight()) return false;
    if (hasHeight()) {
      if (getHeight()
          != other.getHeight()) return false;
    }
    if (hasFoodStatic() != other.hasFoodStatic()) return false;
    if (hasFoodStatic()) {
      if (getFoodStatic()
          != other.getFoodStatic()) return false;
    }
    if (hasFoodPerPlayer() != other.hasFoodPerPlayer()) return false;
    if (hasFoodPerPlayer()) {
      if (java.lang.Float.floatToIntBits(getFoodPerPlayer())
          != java.lang.Float.floatToIntBits(
              other.getFoodPerPlayer())) return false;
    }
    if (hasStateDelayMs() != other.hasStateDelayMs()) return false;
    if (hasStateDelayMs()) {
      if (getStateDelayMs()
          != other.getStateDelayMs()) return false;
    }
    if (hasDeadFoodProb() != other.hasDeadFoodProb()) return false;
    if (hasDeadFoodProb()) {
      if (java.lang.Float.floatToIntBits(getDeadFoodProb())
          != java.lang.Float.floatToIntBits(
              other.getDeadFoodProb())) return false;
    }
    if (hasPingDelayMs() != other.hasPingDelayMs()) return false;
    if (hasPingDelayMs()) {
      if (getPingDelayMs()
          != other.getPingDelayMs()) return false;
    }
    if (hasNodeTimeoutMs() != other.hasNodeTimeoutMs()) return false;
    if (hasNodeTimeoutMs()) {
      if (getNodeTimeoutMs()
          != other.getNodeTimeoutMs()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasWidth()) {
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getWidth();
    }
    if (hasHeight()) {
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
    }
    if (hasFoodStatic()) {
      hash = (37 * hash) + FOOD_STATIC_FIELD_NUMBER;
      hash = (53 * hash) + getFoodStatic();
    }
    if (hasFoodPerPlayer()) {
      hash = (37 * hash) + FOOD_PER_PLAYER_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getFoodPerPlayer());
    }
    if (hasStateDelayMs()) {
      hash = (37 * hash) + STATE_DELAY_MS_FIELD_NUMBER;
      hash = (53 * hash) + getStateDelayMs();
    }
    if (hasDeadFoodProb()) {
      hash = (37 * hash) + DEAD_FOOD_PROB_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDeadFoodProb());
    }
    if (hasPingDelayMs()) {
      hash = (37 * hash) + PING_DELAY_MS_FIELD_NUMBER;
      hash = (53 * hash) + getPingDelayMs();
    }
    if (hasNodeTimeoutMs()) {
      hash = (37 * hash) + NODE_TIMEOUT_MS_FIELD_NUMBER;
      hash = (53 * hash) + getNodeTimeoutMs();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Snakes.GameConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Snakes.GameConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Snakes.GameConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Snakes.GameConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Snakes.GameConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Snakes.GameConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Snakes.GameConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Snakes.GameConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Snakes.GameConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Snakes.GameConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Snakes.GameConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Snakes.GameConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Snakes.GameConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Параметры идущей игры (не должны меняться в процессе игры) 
   * </pre>
   *
   * Protobuf type {@code snakes.GameConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:snakes.GameConfig)
      Snakes.GameConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Snakes.SnakesProto.internal_static_snakes_GameConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Snakes.SnakesProto.internal_static_snakes_GameConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Snakes.GameConfig.class, Snakes.GameConfig.Builder.class);
    }

    // Construct using Snakes.GameConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      width_ = 40;
      bitField0_ = (bitField0_ & ~0x00000001);
      height_ = 30;
      bitField0_ = (bitField0_ & ~0x00000002);
      foodStatic_ = 1;
      bitField0_ = (bitField0_ & ~0x00000004);
      foodPerPlayer_ = 1F;
      bitField0_ = (bitField0_ & ~0x00000008);
      stateDelayMs_ = 1000;
      bitField0_ = (bitField0_ & ~0x00000010);
      deadFoodProb_ = 0.1F;
      bitField0_ = (bitField0_ & ~0x00000020);
      pingDelayMs_ = 100;
      bitField0_ = (bitField0_ & ~0x00000040);
      nodeTimeoutMs_ = 800;
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Snakes.SnakesProto.internal_static_snakes_GameConfig_descriptor;
    }

    @java.lang.Override
    public Snakes.GameConfig getDefaultInstanceForType() {
      return Snakes.GameConfig.getDefaultInstance();
    }

    @java.lang.Override
    public Snakes.GameConfig build() {
      Snakes.GameConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Snakes.GameConfig buildPartial() {
      Snakes.GameConfig result = new Snakes.GameConfig(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.width_ = width_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.height_ = height_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.foodStatic_ = foodStatic_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.foodPerPlayer_ = foodPerPlayer_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.stateDelayMs_ = stateDelayMs_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.deadFoodProb_ = deadFoodProb_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        to_bitField0_ |= 0x00000040;
      }
      result.pingDelayMs_ = pingDelayMs_;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        to_bitField0_ |= 0x00000080;
      }
      result.nodeTimeoutMs_ = nodeTimeoutMs_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Snakes.GameConfig) {
        return mergeFrom((Snakes.GameConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Snakes.GameConfig other) {
      if (other == Snakes.GameConfig.getDefaultInstance()) return this;
      if (other.hasWidth()) {
        setWidth(other.getWidth());
      }
      if (other.hasHeight()) {
        setHeight(other.getHeight());
      }
      if (other.hasFoodStatic()) {
        setFoodStatic(other.getFoodStatic());
      }
      if (other.hasFoodPerPlayer()) {
        setFoodPerPlayer(other.getFoodPerPlayer());
      }
      if (other.hasStateDelayMs()) {
        setStateDelayMs(other.getStateDelayMs());
      }
      if (other.hasDeadFoodProb()) {
        setDeadFoodProb(other.getDeadFoodProb());
      }
      if (other.hasPingDelayMs()) {
        setPingDelayMs(other.getPingDelayMs());
      }
      if (other.hasNodeTimeoutMs()) {
        setNodeTimeoutMs(other.getNodeTimeoutMs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Snakes.GameConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Snakes.GameConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int width_ = 40;
    /**
     * <pre>
     * Ширина поля в клетках (от 10 до 100)
     * </pre>
     *
     * <code>optional int32 width = 1 [default = 40];</code>
     * @return Whether the width field is set.
     */
    @java.lang.Override
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Ширина поля в клетках (от 10 до 100)
     * </pre>
     *
     * <code>optional int32 width = 1 [default = 40];</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }
    /**
     * <pre>
     * Ширина поля в клетках (от 10 до 100)
     * </pre>
     *
     * <code>optional int32 width = 1 [default = 40];</code>
     * @param value The width to set.
     * @return This builder for chaining.
     */
    public Builder setWidth(int value) {
      bitField0_ |= 0x00000001;
      width_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ширина поля в клетках (от 10 до 100)
     * </pre>
     *
     * <code>optional int32 width = 1 [default = 40];</code>
     * @return This builder for chaining.
     */
    public Builder clearWidth() {
      bitField0_ = (bitField0_ & ~0x00000001);
      width_ = 40;
      onChanged();
      return this;
    }

    private int height_ = 30;
    /**
     * <pre>
     * Высота поля в клетках (от 10 до 100)
     * </pre>
     *
     * <code>optional int32 height = 2 [default = 30];</code>
     * @return Whether the height field is set.
     */
    @java.lang.Override
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Высота поля в клетках (от 10 до 100)
     * </pre>
     *
     * <code>optional int32 height = 2 [default = 30];</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }
    /**
     * <pre>
     * Высота поля в клетках (от 10 до 100)
     * </pre>
     *
     * <code>optional int32 height = 2 [default = 30];</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(int value) {
      bitField0_ |= 0x00000002;
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Высота поля в клетках (от 10 до 100)
     * </pre>
     *
     * <code>optional int32 height = 2 [default = 30];</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      bitField0_ = (bitField0_ & ~0x00000002);
      height_ = 30;
      onChanged();
      return this;
    }

    private int foodStatic_ = 1;
    /**
     * <pre>
     * Количество клеток с едой, независимо от числа игроков (от 0 до 100)
     * </pre>
     *
     * <code>optional int32 food_static = 3 [default = 1];</code>
     * @return Whether the foodStatic field is set.
     */
    @java.lang.Override
    public boolean hasFoodStatic() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Количество клеток с едой, независимо от числа игроков (от 0 до 100)
     * </pre>
     *
     * <code>optional int32 food_static = 3 [default = 1];</code>
     * @return The foodStatic.
     */
    @java.lang.Override
    public int getFoodStatic() {
      return foodStatic_;
    }
    /**
     * <pre>
     * Количество клеток с едой, независимо от числа игроков (от 0 до 100)
     * </pre>
     *
     * <code>optional int32 food_static = 3 [default = 1];</code>
     * @param value The foodStatic to set.
     * @return This builder for chaining.
     */
    public Builder setFoodStatic(int value) {
      bitField0_ |= 0x00000004;
      foodStatic_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Количество клеток с едой, независимо от числа игроков (от 0 до 100)
     * </pre>
     *
     * <code>optional int32 food_static = 3 [default = 1];</code>
     * @return This builder for chaining.
     */
    public Builder clearFoodStatic() {
      bitField0_ = (bitField0_ & ~0x00000004);
      foodStatic_ = 1;
      onChanged();
      return this;
    }

    private float foodPerPlayer_ = 1F;
    /**
     * <pre>
     * Количество клеток с едой, на каждого игрока (вещественный коэффициент от 0 до 100)
     * </pre>
     *
     * <code>optional float food_per_player = 4 [default = 1];</code>
     * @return Whether the foodPerPlayer field is set.
     */
    @java.lang.Override
    public boolean hasFoodPerPlayer() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Количество клеток с едой, на каждого игрока (вещественный коэффициент от 0 до 100)
     * </pre>
     *
     * <code>optional float food_per_player = 4 [default = 1];</code>
     * @return The foodPerPlayer.
     */
    @java.lang.Override
    public float getFoodPerPlayer() {
      return foodPerPlayer_;
    }
    /**
     * <pre>
     * Количество клеток с едой, на каждого игрока (вещественный коэффициент от 0 до 100)
     * </pre>
     *
     * <code>optional float food_per_player = 4 [default = 1];</code>
     * @param value The foodPerPlayer to set.
     * @return This builder for chaining.
     */
    public Builder setFoodPerPlayer(float value) {
      bitField0_ |= 0x00000008;
      foodPerPlayer_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Количество клеток с едой, на каждого игрока (вещественный коэффициент от 0 до 100)
     * </pre>
     *
     * <code>optional float food_per_player = 4 [default = 1];</code>
     * @return This builder for chaining.
     */
    public Builder clearFoodPerPlayer() {
      bitField0_ = (bitField0_ & ~0x00000008);
      foodPerPlayer_ = 1F;
      onChanged();
      return this;
    }

    private int stateDelayMs_ = 1000;
    /**
     * <pre>
     * Задержка между ходами (сменой состояний) в игре, в миллисекундах (от 1 до 10000)
     * </pre>
     *
     * <code>optional int32 state_delay_ms = 5 [default = 1000];</code>
     * @return Whether the stateDelayMs field is set.
     */
    @java.lang.Override
    public boolean hasStateDelayMs() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Задержка между ходами (сменой состояний) в игре, в миллисекундах (от 1 до 10000)
     * </pre>
     *
     * <code>optional int32 state_delay_ms = 5 [default = 1000];</code>
     * @return The stateDelayMs.
     */
    @java.lang.Override
    public int getStateDelayMs() {
      return stateDelayMs_;
    }
    /**
     * <pre>
     * Задержка между ходами (сменой состояний) в игре, в миллисекундах (от 1 до 10000)
     * </pre>
     *
     * <code>optional int32 state_delay_ms = 5 [default = 1000];</code>
     * @param value The stateDelayMs to set.
     * @return This builder for chaining.
     */
    public Builder setStateDelayMs(int value) {
      bitField0_ |= 0x00000010;
      stateDelayMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Задержка между ходами (сменой состояний) в игре, в миллисекундах (от 1 до 10000)
     * </pre>
     *
     * <code>optional int32 state_delay_ms = 5 [default = 1000];</code>
     * @return This builder for chaining.
     */
    public Builder clearStateDelayMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      stateDelayMs_ = 1000;
      onChanged();
      return this;
    }

    private float deadFoodProb_ = 0.1F;
    /**
     * <pre>
     * Вероятность превращения мёртвой клетки в еду (от 0 до 1).
     * </pre>
     *
     * <code>optional float dead_food_prob = 6 [default = 0.1];</code>
     * @return Whether the deadFoodProb field is set.
     */
    @java.lang.Override
    public boolean hasDeadFoodProb() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Вероятность превращения мёртвой клетки в еду (от 0 до 1).
     * </pre>
     *
     * <code>optional float dead_food_prob = 6 [default = 0.1];</code>
     * @return The deadFoodProb.
     */
    @java.lang.Override
    public float getDeadFoodProb() {
      return deadFoodProb_;
    }
    /**
     * <pre>
     * Вероятность превращения мёртвой клетки в еду (от 0 до 1).
     * </pre>
     *
     * <code>optional float dead_food_prob = 6 [default = 0.1];</code>
     * @param value The deadFoodProb to set.
     * @return This builder for chaining.
     */
    public Builder setDeadFoodProb(float value) {
      bitField0_ |= 0x00000020;
      deadFoodProb_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Вероятность превращения мёртвой клетки в еду (от 0 до 1).
     * </pre>
     *
     * <code>optional float dead_food_prob = 6 [default = 0.1];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeadFoodProb() {
      bitField0_ = (bitField0_ & ~0x00000020);
      deadFoodProb_ = 0.1F;
      onChanged();
      return this;
    }

    private int pingDelayMs_ = 100;
    /**
     * <pre>
     * Задержка между отправкой ping-сообщений, в миллисекундах (от 1 до 10000)
     * </pre>
     *
     * <code>optional int32 ping_delay_ms = 7 [default = 100];</code>
     * @return Whether the pingDelayMs field is set.
     */
    @java.lang.Override
    public boolean hasPingDelayMs() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * Задержка между отправкой ping-сообщений, в миллисекундах (от 1 до 10000)
     * </pre>
     *
     * <code>optional int32 ping_delay_ms = 7 [default = 100];</code>
     * @return The pingDelayMs.
     */
    @java.lang.Override
    public int getPingDelayMs() {
      return pingDelayMs_;
    }
    /**
     * <pre>
     * Задержка между отправкой ping-сообщений, в миллисекундах (от 1 до 10000)
     * </pre>
     *
     * <code>optional int32 ping_delay_ms = 7 [default = 100];</code>
     * @param value The pingDelayMs to set.
     * @return This builder for chaining.
     */
    public Builder setPingDelayMs(int value) {
      bitField0_ |= 0x00000040;
      pingDelayMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Задержка между отправкой ping-сообщений, в миллисекундах (от 1 до 10000)
     * </pre>
     *
     * <code>optional int32 ping_delay_ms = 7 [default = 100];</code>
     * @return This builder for chaining.
     */
    public Builder clearPingDelayMs() {
      bitField0_ = (bitField0_ & ~0x00000040);
      pingDelayMs_ = 100;
      onChanged();
      return this;
    }

    private int nodeTimeoutMs_ = 800;
    /**
     * <pre>
     * Таймаут, после которого считаем что узел-сосед отпал, в миллисекундах (от 1 до 10000)
     * </pre>
     *
     * <code>optional int32 node_timeout_ms = 8 [default = 800];</code>
     * @return Whether the nodeTimeoutMs field is set.
     */
    @java.lang.Override
    public boolean hasNodeTimeoutMs() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * Таймаут, после которого считаем что узел-сосед отпал, в миллисекундах (от 1 до 10000)
     * </pre>
     *
     * <code>optional int32 node_timeout_ms = 8 [default = 800];</code>
     * @return The nodeTimeoutMs.
     */
    @java.lang.Override
    public int getNodeTimeoutMs() {
      return nodeTimeoutMs_;
    }
    /**
     * <pre>
     * Таймаут, после которого считаем что узел-сосед отпал, в миллисекундах (от 1 до 10000)
     * </pre>
     *
     * <code>optional int32 node_timeout_ms = 8 [default = 800];</code>
     * @param value The nodeTimeoutMs to set.
     * @return This builder for chaining.
     */
    public Builder setNodeTimeoutMs(int value) {
      bitField0_ |= 0x00000080;
      nodeTimeoutMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Таймаут, после которого считаем что узел-сосед отпал, в миллисекундах (от 1 до 10000)
     * </pre>
     *
     * <code>optional int32 node_timeout_ms = 8 [default = 800];</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeTimeoutMs() {
      bitField0_ = (bitField0_ & ~0x00000080);
      nodeTimeoutMs_ = 800;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:snakes.GameConfig)
  }

  // @@protoc_insertion_point(class_scope:snakes.GameConfig)
  private static final Snakes.GameConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Snakes.GameConfig();
  }

  public static Snakes.GameConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<GameConfig>
      PARSER = new com.google.protobuf.AbstractParser<GameConfig>() {
    @java.lang.Override
    public GameConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GameConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GameConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Snakes.GameConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

